### ISSUE TITLE
add INPUT query to cloud API

### ISSUE THREAD

**Issue by manitou48** [littlebits/cloud-platform#1]
The subscription model serves its purpose in the cloud http API, I guess, but it would be nice to have a simple INPUT query, like the OUTPUT set. So in curl-speak it would be

curl -i -XGET -H "Authorization: ... -H "Accept: ...json" https://api-.../devices/DEVICEID/input2

and then the json reply would give the current voltage or percentage from the cloudbit input pin. You could use the same json data structure that cloudcontrol receive uses, or something simpler, e.g.
{
"name": "amplitude", "percent": intval>
}

**Comment by NelsonMinar** [comment]
I realize this issue is closed, but I'm baffled why there's not a simple HTTP call to show me the current value of the device. Subscriptions and streams are nifty but way more complicated; why can't I just poll for the number?

**Comment by jasonkuhrt** [comment]
@NelsonMinar thanks for the feedback! V3 isn't stable yet so things could change.

I haven't seen any useful use-cases outlined for request-response on what is fundamentally an infinite stream of data;

> current value of the device

So that's the thing, there is no *current value*.

> way more complicated

How so? Polling is the mechanism with actually more machinery at work not to mention conceptually more complicated and with more indirection.

> why can't I just poll for the number?

Why can't you just close the connection after your first data event?

Streaming is not more complicated, its just different. I see a lot FUD around how streaming is "harder" so excuse me if I'm not understanding you clearly.

**Comment by NelsonMinar** [comment]
I'm thinking from the point of view of a developer who wants to quickly try an experiment. Sorry if my comment seemed snarky, I was in the middle of the exercise of writing my first client and found it remarkably difficult to just get the number I can see on the web page out of the device.

The rest of the product is so easy to use, I think a simple poll interface would be a nice match to littleBits ease-of-entry. OTOH when I went looking for the poll interface I didn't appreciate your data model is really a stream off the live device. I guess I was expecting to just be able to poll for the last reading your system had seen, but maybe that's not consistent with the product vision.

FWIW, here's the simplest Python Requests code I could come up with to read the number off the device:

````
resp = requests.get('https://api-http.littlebitscloud.cc/devices/%s/input' % device,
                    headers=headers,
                    stream=True,
                    timeout=5)
output = next(resp.iter_lines(decode_unicode='ascii'))
resp.close()
data = json.loads(output.lstrip('data:'))
print(data['percent'])
````

with a polling interface, that could be something like

````
resp = requests.get('https://api-http.littlebitscloud.cc/devices/%s/input' % device,
                    headers=headers)
data = resp.json()
print(data['percent'])
````

Requests is pretty awkward when dealing with the streaming data; you have to know to set `stream=True`, you have to fake out the iterator protocol to get the data when it comes, and you can't use Requests' built-in JSON decoder.

Anyway thanks for providing the stream, it's definitely simpler than the subscription mechanism.

**Comment by jasonkuhrt** [comment]
@NelsonMinar Thanks for explaining your journey. Better docs and general on boarding (interactive demos etc.) are among the things we think are missing most right now, and we're certainly putting effort into improving the story around that.

The platform we're building is real-time stream-oriented. We believe the Cloud Platform we're building is fairly unique but that means certain RESTful traditions won't apply to us. We think that's fine, but we know tooling is lacking for stream-oriented programming in general so we're very open about how to lower the barrier to this powerful paradigm of programming. In your case it doesn't help that we also have no official python client (currently we provide an official JavaScript client) but based on user-feedback it seems to be a lively part of our user-base so that could change in the future!

**Comment by manitou48** [comment]
jason, what is the current API for INPUT.  my python doesn't work for INPUT anymore.  I can't even get curl to work -- what is current syntax for an INPUT request ?  reference URL?
thanks

**Comment by stresslimit** [comment]
We do have an open issue to allow the `input` endpoint accept an arg so you can decide whether you want a single transient value or a stream. I think that will help when we get there.

The "current" documented API version is `v2`, and the input is in `v3` which is in soft-launch right now [it's live but not heavily documented or supported. So if you are cURLing input you have to have v3 in the header or url. Example here: https://github.com/littlebits/cloud-api-lessons#lesson-2-read-from-cloudbit

**Comment by manitou48** [comment]
i had tried the v3 curl example it failed with 400

curl -i -H "Authorization: Bearer ec77a8cae80d0699ba4082b23ec96ad72b97b814f2e5f3ed08fbaf69b4fac8dc" https://api-http.littlebitscloud.cc/v3/devices/243c200bffd5/input
HTTP/1.1 400 Bad Request

so maybe v3 requests not being supported today?

thanks
On Thu, Feb 12, 2015 at 10:58:05AM -0800, Colin wrote:
> We do have an open issue to allow the `input` endpoint accept an arg so you can decide whether you want a single transient value or a stream. I think that will help when we get there.
> 
> The "current" documented API version is `v2`, and the input is in `v3` which is in soft-launch right now [it's live but not heavily documented or supported. So if you are cURLing input you have to have v3 in the header or url. Example here: https://github.com/littlebits/cloud-api-lessons#lesson-2-read-from-cloudbit
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/littlebits/cloud-platform/issues/1#issuecomment-74129796

-- 
  Tom Dunigan  thdunigan@gmail.com   http://tnlandforms.us

**Comment by technoboy10** [comment]
Yep, getting 400 errors as well.

```
for i in bit.raw_stream():
    print i
 
{"statusCode":404,"error":"Not Found"}
```

**Comment by stresslimit** [comment]
@manitou48 @technoboy10 looks like you may have found a bug, we're investigating now.

**Comment by stresslimit** [comment]
We've deployed a fix for the bug identified in this issue for `GET /input`, please let us know that all looks good now!

**Comment by technoboy10** [comment]
@stresslimit Yep, back to normal. (Turns out my 404 was a coding error on my part, but curl works again)
